### ISSUE TITLE
Not working on AlmaLinux

### ISSUE THREAD

**Issue by andrr2** [thomaswilbur/cPanel-OpenLitespeed#1]
Tried on AlmaLinux but is not working. 
OLS is installing indeed and configurations imported but websites are timeout/not reachable.
Could you please make a more detailed install ? 
Eg. System requirments and other .. 
Thanks!

**Comment by thomaswilbur** [comment]
Hi,

I have tested and it does work on my server. Can you send me a screenshot of the Litespeed Admin Panel eg https://<my-server-ip>:7080. If you can't access it try disabling the firewall and see if that fixes your issue. If you can can you screenshot the entire dashboard. Also can you send a zip file of the entire /usr/local/lsws/conf folder.

**Comment by andrr2** [comment]
Hi thomas,
Is not working out of the box ... to work fs.enforce_symlinksifowner=1 you have to install Symlink Protection Patch from kernel care...
Could you please write a more detailed instructions ? Because as i said is not working on almalinux out of the box .. you have to do some tweaks/install before.

**Comment by thomaswilbur** [comment]
Were you able to get it working then? You made no mention of websites timing out this time.

**Comment by andrr2** [comment]
No i wasn't able to get working .. restored my backup..
I have around 50 website's on my cpanel server and none of them working. 
I disabled csf/firewalld but with no succes. I can connect to openlitespeed admin (7080) .. openlitespeed works great .

**Comment by thomaswilbur** [comment]
Okay, were listeners showing up in the admin panel? Can you send a screenshot of that, and a zip file of /usr/local/lsws/conf so I can check for myself.

**Comment by andrr2** [comment]
Ok let me do another backup to my server and retry ..

**Comment by thomaswilbur** [comment]
You can send the files to me via discord if you would perfer, My discord id is idodia#9201

**Comment by andrr2** [comment]
If added you on discord. Let's talk there.

**Comment by thomaswilbur** [comment]
Notes: This server had some customizations done, a manual PHP override needs to be added
